obj-$(CONFIG_BATTERY_SAMSUNG)		+= sec_battery.o sec_battery_vote.o sec_battery_thermal.o sec_battery_sysfs.o sec_battery_dt.o sec_battery_ttf.o
obj-$(CONFIG_OF)			+= sec_adc.o
obj-$(CONFIG_MULTI_CHARGING)		+= sec_multi_charger.o
obj-$(CONFIG_DUAL_BATTERY)		+= sec_dual_battery.o
obj-$(CONFIG_STEP_CHARGING)		+= sec_step_charging.o
obj-$(CONFIG_BATTERY_CISD)		+= sec_cisd.o
obj-$(CONFIG_WIRELESS_AUTH)		+= sec_battery_misc.o
obj-$(CONFIG_DIRECT_CHARGING)		+= sec_direct_charger.o
obj-$(CONFIG_UPDATE_BATTERY_DATA)	+= sec_battery_data.o
obj-$(CONFIG_BATTERY_NOTIFIER)		+= battery_notifier.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= sec_pd.o

ccflags-y := -Wformat
