obj-$(CONFIG_CHARGER_PCA9468)	+= pca9468_charger.o
obj-$(CONFIG_PM_S2MU106)  		+= s2mu106_pmeter.o
obj-$(CONFIG_CHARGER_S2MU106)   += s2mu106_charger.o
obj-$(CONFIG_CHARGER_SM5440)   += sm5440_charger.o
