obj-$(CONFIG_CAMERA_COMPANION_CHIP_SELECT) += fimc-is-companion.o

obj-$(CONFIG_CAMERA_COMPANION_CHIP_GC607_OBJ) += fimc-is-companion-gc607.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor
